import type { SizeMode } from "@/lib/trade/types";
import { APP_VERSION } from "./app";

export interface SideLabels {
	buy: string;
	sell: string;
	buyAria: string;
	sellAria: string;
}

export function getSideLabels(isSpotMarket: boolean): SideLabels {
	if (isSpotMarket) {
		return { buy: "Buy", sell: "Sell", buyAria: "Buy", sellAria: "Sell" };
	}
	return { buy: "Long", sell: "Short", buyAria: "Buy Long", sellAria: "Sell Short" };
}

export function getSizeModeLabel(sizeMode: SizeMode, baseToken: string, quoteToken: string): string {
	return sizeMode === "base" ? baseToken || "---" : quoteToken;
}

export const UI_TEXT = {
	COMMON: {
		CLOSE: "Close",
		LOADING: "Loading",
	},
	NOT_FOUND: {
		CODE: "404",
		TITLE: "Page not found",
		DESCRIPTION: "The page you are looking for does not exist.",
		CTA_LABEL: "Go to trading terminal",
		CTA_ARIA: "Go to trading terminal",
	},
	TOP_NAV: {
		BRAND_PREFIX: "HYPE",
		BRAND_SUFFIX: "TERMINAL",
		NAV_ITEMS: ["Trade", "Vaults", "Portfolio", "Staking", "Leaderboard"],
		MORE_LABEL: "More",
		MORE_ARIA: "More options",
		MORE_MENU_ITEMS: ["API", "Docs", "Support"],
		DEPOSIT_LABEL: "Deposit",
		NOTIFICATIONS_ARIA: "Notifications",
		SETTINGS_ARIA: "Settings",
	},
	GLOBAL_SETTINGS: {
		TITLE: "Settings",
		DESCRIPTION: "Global preferences for trading, chart, and orderbook.",
		SECTION_TRADING: "Trading",
		SECTION_CHART: "Chart",
		SECTION_ORDERBOOK: "Orderbook",
		SLIPPAGE_LABEL: "Max slippage",
		SLIPPAGE_HELP: "Used for market orders and position closes.",
		SLIPPAGE_UNIT: "bps",
		SHOW_ORDERS: "Show orders on chart",
		SHOW_POSITIONS: "Show positions on chart",
		SHOW_EXECUTIONS: "Show executions on chart",
		SHOW_SCANLINES: "Show chart scanlines",
		SHOW_ORDERBOOK_USD: "Show orderbook size in USD",
	},
	USER_MENU: {
		COPY_ADDRESS: "Copy Address",
		CONNECTING: "Connecting...",
		CONNECT_WALLET: "Connect Wallet",
		ADD_FUNDS: "Add funds",
		DISCONNECT: "Disconnect",
	},
	THEME_TOGGLE: {
		SWITCH_LIGHT: "Switch to light mode",
		SWITCH_DARK: "Switch to dark mode",
		LIGHT: "Light",
		DARK: "Dark",
	},
	BREADCRUMB: {
		ARIA_LABEL: "breadcrumb",
		ELLIPSIS_LABEL: "More",
	},
	PAGINATION: {
		ARIA_LABEL: "pagination",
		PREVIOUS_LABEL: "Previous",
		NEXT_LABEL: "Next",
		PREVIOUS_ARIA: "Go to previous page",
		NEXT_ARIA: "Go to next page",
		ELLIPSIS_LABEL: "More pages",
	},
	SIDEBAR: {
		TITLE: "Sidebar",
		DESCRIPTION: "Displays the mobile sidebar.",
		TOGGLE_LABEL: "Toggle Sidebar",
	},
	VIRTUAL_TABLE: {
		SORT_ARIA: (label: string) => `Sort by ${label}`,
	},
	FAVORITES: {
		EMPTY: "Select favorite markets",
		SELECT_MARKET_ARIA: (coin: string) => `Select ${coin} market`,
	},
	ORDERBOOK: {
		BOOK_LABEL: "Order Book",
		TRADES_LABEL: "Trades",
		ORDER_BOOK_ARIA: "Order Book",
		RECENT_TRADES_ARIA: "Recent Trades",
		SELECT_AGGREGATION_ARIA: "Select order book aggregation",
		AUTO_LABEL: "Auto",
		SIG_FIGS_SUFFIX: "sig figs",
		HEADER_PRICE: "Price",
		HEADER_SIZE: "Size",
		HEADER_TOTAL: "Total",
		FAILED: "Failed to load order book.",
		WAITING: "Waiting for order book...",
		SPREAD_LABEL: "Spread",
		WEBSOCKET_ERROR: "WebSocket error",
		APPROX_PREFIX: "≈ ",
	},
	TRADES: {
		HEADER_TIME: "Time",
		HEADER_PRICE: "Price",
		HEADER_SIZE: "Size",
		FAILED: "Failed to load trades.",
		WAITING: "Waiting for trades...",
		WEBSOCKET_ERROR: "WebSocket error",
	},
	FOOTER: {
		STATUS_CONNECTED: "Connected",
		BLOCK_LABEL: "Block:",
		GAS_LABEL: "Gas:",
		LATENCY_LABEL: "Latency:",
		VERSION: APP_VERSION,
	},
	ORDER_TOAST: {
		TITLE: "Order Queue",
		PENDING_LABEL: "pending",
		FAILED_LABEL: "failed",
		DISMISS_ARIA: "Dismiss",
		SIZE_LABEL: "Size",
		FILLED_SUFFIX: "% filled",
	},
	ACCOUNT_PANEL: {
		ARIA_EXPAND: "Expand account panel",
		ARIA_COLLAPSE: "Collapse account panel",
		TITLE: "Account",
		EQUITY_LABEL: "Equity",
		PNL_LABEL: "PNL",
		TAB_PERPS: "Perps",
		TAB_SPOT: "Spot",
		CONNECT: "Connect wallet to view account",
		LOADING: "Loading...",
		BALANCE_LABEL: "Balance",
		UNREALIZED_LABEL: "Unrealized PNL",
		AVAILABLE_LABEL: "Available",
		MARGIN_USED_LABEL: "Margin Used",
		MARGIN_RATIO_LABEL: "Margin Ratio",
		CROSS_LEVERAGE_LABEL: "Cross Leverage",
		DEPOSIT_LABEL: "Deposit",
		WITHDRAW_LABEL: "Withdraw",
	},
	BALANCES_TAB: {
		TITLE: "Account Balances",
		CONNECT: "Connect your wallet to view balances.",
		LOADING: "Loading balances...",
		FAILED: "Failed to load balances.",
		EMPTY: "No balances found. Deposit funds to start trading.",
		HEADER_ASSET: "Asset",
		HEADER_AVAILABLE: "Available",
		HEADER_IN_USE: "In Use",
		HEADER_TOTAL: "Total",
		HEADER_USD_VALUE: "USD Value",
		TYPE_PERP: "perp",
		TYPE_SPOT: "spot",
	},
	POSITIONS_TAB: {
		TITLE: "Active Positions",
		CONNECT: "Connect your wallet to view positions.",
		LOADING: "Loading positions...",
		FAILED: "Failed to load positions.",
		EMPTY: "No active positions.",
		HEADER_ASSET: "Asset",
		HEADER_SIZE: "Size",
		HEADER_VALUE: "Value",
		HEADER_ENTRY: "Entry",
		HEADER_MARK: "Mark",
		HEADER_PNL: "PNL",
		HEADER_LIQ: "Liq",
		HEADER_ACTIONS: "Actions",
		SIDE_LONG: "Long",
		SIDE_SHORT: "Short",
		ACTION_CLOSE: "Close",
		ACTION_CLOSING: "Closing...",
		ACTION_TPSL: "TP/SL",
		ARIA_CLOSE: "Close position",
		ARIA_TPSL: "Set TP/SL",
		ERROR_SIGNER: "Connect a wallet to manage positions.",
		ERROR_CLOSE_FALLBACK: "Unable to close position.",
	},
	ORDERS_TAB: {
		TITLE: "Open Orders",
		CONNECT: "Connect your wallet to view open orders.",
		LOADING: "Loading open orders...",
		FAILED: "Failed to load open orders.",
		EMPTY: "No open orders.",
		HEADER_ASSET: "Asset",
		HEADER_TYPE: "Type",
		HEADER_PRICE: "Price",
		HEADER_SIZE: "Size",
		HEADER_FILLED: "Filled",
		HEADER_STATUS: "Status",
		HEADER_ACTIONS: "Actions",
		SIDE_BUY: "buy",
		SIDE_SELL: "sell",
		TYPE_LIMIT: "limit",
		TYPE_LIMIT_RO: "limit ro",
		STATUS_OPEN: "open",
		ACTION_CANCEL: "Cancel",
		ACTION_CANCELING: "Canceling...",
		ACTION_CANCEL_SELECTED: "Cancel selected",
		ACTION_CANCEL_ALL: "Cancel all",
		ARIA_CANCEL: "Cancel order",
		ARIA_CANCEL_SELECTED: "Cancel selected orders",
		ARIA_CANCEL_ALL: "Cancel all orders",
		ARIA_SELECT_ALL: "Select all orders",
		ARIA_SELECT_ORDER: "Select order",
		ERROR_SIGNER: "Connect a wallet to manage orders.",
		ERROR_MARKET_UNAVAILABLE: "Market metadata unavailable.",
		ERROR_CANCEL_FALLBACK: "Unable to cancel orders.",
	},
	FUNDING_TAB: {
		TITLE: "Funding Payments",
		CONNECT: "Connect your wallet to view funding payments.",
		LOADING: "Loading funding history...",
		FAILED: "Failed to load funding history.",
		EMPTY: "No funding payments found.",
		HEADER_ASSET: "Asset",
		HEADER_POSITION: "Position",
		HEADER_RATE: "Rate",
		HEADER_PAYMENT: "Payment",
		HEADER_TIME: "Time",
		SIDE_LONG: "Long",
		SIDE_SHORT: "Short",
	},
	HISTORY_TAB: {
		TITLE: "Trade History",
		COUNT_LABEL: "Trades",
		CONNECT: "Connect your wallet to view trade history.",
		LOADING: "Loading trade history...",
		FAILED: "Failed to load trade history.",
		EMPTY: "No fills found.",
		HEADER_ASSET: "Asset",
		HEADER_TYPE: "Type",
		HEADER_PRICE: "Price",
		HEADER_SIZE: "Size",
		HEADER_FEE: "Fee",
		HEADER_PNL: "PNL",
		HEADER_TIME: "Time",
		SIDE_BUY: "buy",
		SIDE_SELL: "sell",
	},
	TWAP_TAB: {
		TITLE: "TWAP Orders",
		COUNT_LABEL: "Active",
		CONNECT: "Connect your wallet to view TWAP orders.",
		LOADING: "Loading TWAP orders...",
		FAILED: "Failed to load TWAP history.",
		EMPTY: "No TWAP orders found.",
		HEADER_ASSET: "Asset",
		HEADER_TOTAL_SIZE: "Total Size",
		HEADER_EXECUTED: "Executed",
		HEADER_AVG_PRICE: "Avg Price",
		HEADER_PROGRESS: "Progress",
		HEADER_STATUS: "Status",
		HEADER_ACTIONS: "Actions",
		SIDE_BUY: "buy",
		SIDE_SELL: "sell",
		STATUS_ACTIVE: "active",
		STATUS_COMPLETED: "completed",
		STATUS_CANCELLED: "cancelled",
		ACTION_CANCEL: "Cancel",
		ARIA_CANCEL: "Cancel TWAP order",
	},
	DEPOSIT_MODAL: {
		TITLE: "Deposit Funds",
		DESCRIPTION: "Transfer USDC to your Hyperliquid account to start trading.",
		BUTTON_LABEL: "Deposit on Hyperliquid",
		HELP_TEXT: "Bridge USDC from Arbitrum or other chains to your Hyperliquid account.",
	},
	WALLET_DIALOG: {
		TITLE: "Connect Wallet",
		EMPTY: "No wallets found",
	},
	ORDER_ENTRY: {
		ERROR_NOT_CONNECTED: "Not connected",
		ERROR_LOADING_WALLET: "Loading wallet...",
		ERROR_NO_BALANCE: "No balance",
		ERROR_NO_MARKET: "No market",
		ERROR_MARKET_NOT_READY: "Market not ready",
		ERROR_SIGNER_NOT_READY: "Signer not ready",
		ERROR_NO_MARK_PRICE: "No mark price",
		ERROR_LIMIT_PRICE: "Enter limit price",
		ERROR_SIZE: "Enter size",
		ERROR_MIN_NOTIONAL: "Min order value $10",
		ERROR_EXCEEDS_MAX: "Exceeds max size",
		BUTTON_CONNECT: "Connect Wallet",
		BUTTON_SWITCHING: "Switching...",
		BUTTON_SWITCH_CHAIN: "Switch to Arbitrum",
		BUTTON_DEPOSIT: "Deposit",
		BUTTON_SIGNING: "Signing...",
		BUTTON_LOADING: "Loading...",
		BUTTON_ENABLE_TRADING: "Enable Trading",
		BUTTON_BUY: "Buy",
		BUTTON_SELL: "Sell",
		MODE_CROSS: "Cross",
		MODE_ISOLATED: "Isolated",
		MODE_COMING_SOON: "Coming soon",
		LEVERAGE_ARIA: "Select leverage",
		ORDER_TYPE_MARKET: "Market",
		ORDER_TYPE_LIMIT: "Limit",
		ORDER_TYPE_STOP: "Stop",
		BUY_LABEL: "Long",
		SELL_LABEL: "Short",
		BUY_ARIA: "Buy Long",
		SELL_ARIA: "Sell Short",
		AVAILABLE_LABEL: "Available",
		DEPOSIT_LABEL: "Deposit",
		POSITION_LABEL: "Position",
		SIZE_LABEL: "Size",
		SIZE_MODE_TOGGLE_ARIA: "Toggle size mode",
		SIZE_MODE_USD: "USD",
		SIZE_MODE_FALLBACK: "---",
		INPUT_PLACEHOLDER: "0.00",
		SIZE_MAX_LABEL: "Max",
		PERCENT_ARIA: (percent: number) => `Set ${percent}%`,
		LIMIT_PRICE_LABEL: "Limit Price",
		MARK_PRICE_LABEL: "Mark",
		REDUCE_ONLY_LABEL: "Reduce Only",
		TPSL_LABEL: "TP/SL",
		TPSL_ARIA: "Take Profit / Stop Loss",
		SUMMARY_LIQ: "Liq. Price",
		SUMMARY_ORDER_VALUE: "Order Value",
		SUMMARY_MARGIN_REQ: "Margin Req.",
		SUMMARY_SLIPPAGE: "Slippage",
		SUMMARY_FEE: "Est. Fee",
		APPROVAL_ERROR_FALLBACK: "Failed to enable trading",
		ORDER_ERROR_FALLBACK: "Order failed",
	},
	MARKET_OVERVIEW: {
		LABEL_MARK: "MARK",
		LABEL_ORACLE: "ORACLE",
		LABEL_VOLUME: "VOL",
		LABEL_OPEN_INTEREST: "OI",
	},
	TOKEN_SELECTOR: {
		HEADER_MARKET: "Market",
		HEADER_PRICE: "Price",
		HEADER_CHANGE_24H: "24h Price",
		HEADER_OPEN_INTEREST: "Open Interest",
		HEADER_VOLUME: "Volume",
		HEADER_FUNDING: "Funding",
		ARIA_SELECT: "Select token",
		SEARCH_PLACEHOLDER: "Search markets...",
		FILTER_ARIA: (label: string) => `Filter by ${label}`,
		SORT_ARIA: (label: string) => `Sort by ${label}`,
		LOADING: "Loading markets...",
		EMPTY: "No markets found.",
		FAVORITE_ADD: "Add to favorites",
		FAVORITE_REMOVE: "Remove from favorites",
		NEW_BADGE: "NEW",
		MARKETS_SUFFIX: "markets",
		UPDATED_LIVE: "Updated live",
		SORTED_BY: (id: string) => `Sorted by ${id}`,
	},
	CHART_DATAFEED: {
		ERROR_UNKNOWN_SYMBOL: (symbol: string) => `Unknown symbol: ${symbol}`,
		ERROR_UNSUPPORTED_RESOLUTION: (resolution: string) => `Unsupported resolution: ${resolution}`,
	},
	TRADING_AGENT: {
		ERROR_WALLET_CLIENT_NOT_READY: "Wallet client not ready. Please wait and try again.",
		ERROR_WALLET_NOT_CONNECTED: "Wallet not connected",
		ERROR_CREATE_WALLET: "Failed to create wallet",
		AGENT_NAME: "HypeTerminal",
	},
	ERRORS: {
		GENERIC_FALLBACK: "Something went wrong.",
	},
} as const;
